server:
  port: 8080
  servlet:
    context-path: /identity

# Identity Service Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: dat123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
